### ISSUE TITLE
Feature Request: Close BufferTree window on select

### ISSUE THREAD

**Issue by dusktreader** [el-iot/buffer-tree-explorer#7]
I would like to have the BufferTree window close when I select a buffer. Ideally, this would behavior would be controllable with a flag.

For example NERDTree enables this behavior with the `NERDTreeQuitOnOpen` flag.

Lacking this, buffer-tree-explorer isn't a viable replacement for bufexplorer for my workflow.

Love the plugin, though! I'm working on a work-around for this, but I would still like to see this functionality supported in the plugin.

**Comment by el-iot** [comment]
Hey! You're right - this is a dead-obvious improvement that I have been neglecting. I've just added it now - let me know what you think!

**Comment by dusktreader** [comment]
Beautiful! Thank you so much!
